custom: 
  - "TRX: TRc8nwBDaW8QMfT8AdsMkv8bfdYNbLgvcv"
  - "BTC: bc1qdk5rdgum0caqrvz6uljk2jm7hxwzrkt259smzn"
  - "ETH: 0x9c59C80a1c1521f0ab22ACc911f4493E4E7538D7"
  - "XLM: GCTFF5NQ7ZOD6IDNFUXB6QIRAKDZPHSLHVHV6V5TPDP2Q74DE3METPEC"
